### ISSUE TITLE
December 2023 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#1030]
This issue is to track tasks related to the December 2023 spec release.

* [x] Merge any last-minute fixes
    * [x] #1031
    * [x] #1032 (possibly)
    * [x] #1033 
    * [x] #1034
* [x] Add extension headers to OpenCL-Headers
    * [x] https://github.com/KhronosGroup/OpenCL-Headers/pull/244
* [x] ~~Update OpenCL C++ bindings~~ (nothing more planned)
* [x] Update OpenCL-SDK submodules and project version
    * [x] https://github.com/KhronosGroup/OpenCL-SDK/pull/95
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.15
* [x] Build the specs and create an OpenCL-Registry PR to publish them
    * [x] https://github.com/KhronosGroup/OpenCL-Registry/pull/144
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them
    * [x] https://github.com/KhronosGroup/OpenCL-Registry/pull/145
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2023.12.14
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2023.12.14
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2023.04.17
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2023.12.14
* [x] CTS Issues/PRs for new extensions - all needed issues filed.
* [x] Coordinate announcements

**Comment by bashbaug** [comment]
All tasks are complete - closing!
