### ISSUE TITLE
April 2024 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#1143]
This issue is to track tasks related to the April 2024 spec release.

* [x] Merge any last-minute fixes - done!
* [x] Add extension headers to OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/pull/249
* [x] Update OpenCL C++ bindings - https://github.com/KhronosGroup/OpenCL-CLHPP/pull/291
* [x] Update OpenCL-SDK submodules and project version - https://github.com/KhronosGroup/OpenCL-SDK/pull/103
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.16
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/150
    * [x] Check that all links work as expected
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/151
    * [x] Check that all links work as expected
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2024.05.08
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2024.05.08
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2024.05.08
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2024.05.08
* [x] CTS Issues/PRs for new extensions
    * [x] cl_khr_kernel_clock - https://github.com/KhronosGroup/OpenCL-CTS/pull/1960
* [x] Coordinate announcements

**Comment by bashbaug** [comment]
All tasks are complete - closing!
