### ISSUE TITLE
October 2024 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#1271]
This issue is to track tasks related to the October 2024 spec release.

* [x] Check: not in this release?
    * https://github.com/KhronosGroup/OpenCL-Docs/pull/850
    * https://github.com/KhronosGroup/OpenCL-Headers/pull/265
    * https://github.com/KhronosGroup/OpenCL-CLHPP/pull/307
    * https://github.com/KhronosGroup/OpenCL-Headers/issues/266
* [x] Merge any last-minute fixes
    * [x] https://github.com/KhronosGroup/OpenCL-Docs/pull/1272
    * [x] https://github.com/KhronosGroup/OpenCL-Docs/pull/1245
    * [x] https://github.com/KhronosGroup/OpenCL-Docs/pull/1273
    * [x] https://github.com/KhronosGroup/OpenCL-Docs/pull/1274
* [x] Add extension headers to OpenCL-Headers
    * [x] https://github.com/KhronosGroup/OpenCL-Headers/pull/264
* [x] Update OpenCL C++ bindings
    * [x] https://github.com/KhronosGroup/OpenCL-CLHPP/pull/302 (nice-to-have)
* [x] Temporarily disable the PPA parts of the release script for the following repos:
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/pull/267
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/pull/243
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/pull/312
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/pull/114 (also updates submodules and project version)
* [x] Update OpenCL-SDK submodules and project version
    * [x] https://github.com/KhronosGroup/OpenCL-SDK/pull/114
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.17
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/160
    * [x] Check that all links work as expected
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/161
    * [x] Check that all links work as expected
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * Status: Tagging is done.  There was an issue with the automated OpenCL SDK release that we are working through, so releases are not done (yet).
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2024.10.24
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2024.10.24
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2024.10.24
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2024.10.24
* [x] CTS Issues/PRs for new extensions
    * [x] cl_khr_external_memory v1.1 - https://github.com/KhronosGroup/OpenCL-CTS/pull/1895
* [x] Coordinate announcements

**Comment by bashbaug** [comment]
All tasks are complete - closing!
