### ISSUE TITLE
December 2020 Maintenance Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#528]
This issue is to track tasks related to the December 2020 spec maintenance release.

- [x] Merge any last-minute editorial fixes.
- [x] Tag the spec sources - [v3.0.6](https://github.com/KhronosGroup/OpenCL-Docs/tree/v3.0.6).
- [x] Build the specs.
- [x] OpenCL-Registry PR to publish the specs - https://github.com/KhronosGroup/OpenCL-Registry/pull/91.
- [x] Update OpenCL-SDK submodules - https://github.com/KhronosGroup/OpenCL-SDK/pull/19
- [x] Tag additional ecosystem repos:
    - [x] OpenCL-Headers - [v2020.12.18](https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2020.12.18)
    - [x] OpenCL-CLHPP - [v2.0.13](https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2.0.13)
    - [x] OpenCL-ICD-Loader - [v2020.12.18](https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2020.12.18)
    - [x] ~~OpenCL-CTS~~ (marked complete but not done, not needed)
    - [x] OpenCL-SDK? - [v2020.12.18](https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2020.12.18)

**Comment by AnastasiaStulova** [comment]
>  Build the specs (or use the CI artifacts from the tag).

There is one small issue on the attached documents from Travis builds that the branch is not reported correctly in the document, only the tag and the commit are listed. This is because for Travis seems to checkout the commit for building tags so it is no longer on any branch. I am not sure how important this is though but I just want to point this out just in case.

**Comment by alycm** [comment]
OpenCL-CTS should maybe not be tagged because it follows it's own date based scheme?

**Comment by bashbaug** [comment]
I think we're all done!  Closing.

**Comment by bashbaug** [comment]
Note for next time: in addition to tagging the ecosystem repos, we also need to do releases for at least some of them (headers, C++ bindings, ICD loader?, SDK?).
