### ISSUE TITLE
April 2021 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#606]
This issue is to track tasks related to the April 2021 spec release.

* [x] Merge any last-minute fixes.
* [x] Tag the spec sources - [v3.0.7](https://github.com/KhronosGroup/OpenCL-Docs/tree/v3.0.7).
* [x] Build the specs.
* [x] OpenCL-Registry PR to publish the specs - https://github.com/KhronosGroup/OpenCL-Registry/pull/97.
* [x] Add extension headers to OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/pull/166.
* [x] Update OpenCL C++ bindings - https://github.com/KhronosGroup/OpenCL-CLHPP/pull/135 https://github.com/KhronosGroup/OpenCL-CLHPP/pull/136
* [x] Update OpenCL-SDK submodules - https://github.com/KhronosGroup/OpenCL-SDK/pull/29
* [x] Tag and release additional ecosystem repos:
    * [x] OpenCL-Headers - [v2021.04.29](https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2021.04.29)
    * [x] OpenCL-CLHPP - [v2.0.14](https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2.0.14)
    * [x] OpenCL-ICD-Loader - [v2021.04.29](https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2021.04.29)
    * [x] OpenCL-SDK - [v2021.04.29](https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2021.04.29)
* [x]  CTS PRs for new extensions:
    * [x] cl_khr_spirv_extended_debug_info - see https://github.com/KhronosGroup/OpenCL-CTS/issues/1425
    * [x] cl_khr_pci_bus_info - https://github.com/KhronosGroup/OpenCL-CTS/pull/1227
    * [x] cl_khr_extended_bit_ops - https://github.com/KhronosGroup/OpenCL-CTS/pull/1232
    * [x] cl_khr_suggested_local_work_size - https://github.com/KhronosGroup/OpenCL-CTS/pull/1225
    * [x] cl_khr_spirv_linkonce_odr - https://github.com/KhronosGroup/OpenCL-CTS/pull/1226
* [x] Tidy up automated spec release error.

**Comment by bashbaug** [comment]
I created an issue for the missing CTS coverage, so closing this issue.
