### ISSUE TITLE
June 2021 Release Checklist

### ISSUE THREAD

**Issue by alycm** [KhronosGroup/OpenCL-Docs#634]
This issue is to track tasks related to the June 2021 spec release.

* [x] Merge any last-minute fixes
* [x] Tag the spec sources
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/98
* [x] Add extension headers to OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/pull/170
* [x] Update OpenCL C++ bindings - https://github.com/KhronosGroup/OpenCL-CLHPP/pull/137
* [x] Update OpenCL-SDK submodules - https://github.com/KhronosGroup/OpenCL-SDK/pull/33
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2021.06.30
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2.0.15
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2021.06.30
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2021.07.01
* [x]  CTS PRs for new extensions:
    * [x] cl_khr_integer_dot_product - https://github.com/KhronosGroup/OpenCL-CTS/pull/1276

**Comment by bashbaug** [comment]
All tasks are done!  Closing.
