### ISSUE TITLE
October 2021 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#694]
This issue is to track tasks related to the October 2021 spec release.

* [x] Merge any last-minute fixes
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.9
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/106
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/108
* [x] Add extension headers to OpenCL-Headers
    * [x] https://github.com/KhronosGroup/OpenCL-Headers/pull/174
    * [x] https://github.com/KhronosGroup/OpenCL-Headers/pull/180
* [ ] Update OpenCL C++ bindings
    * [x] https://github.com/KhronosGroup/OpenCL-CLHPP/pull/141
    * [ ] https://github.com/KhronosGroup/OpenCL-CLHPP/issues/154
    * [ ] https://github.com/KhronosGroup/OpenCL-CLHPP/issues/155
    * [ ] https://github.com/KhronosGroup/OpenCL-CLHPP/issues/156
* [ ] Update OpenCL-SDK submodules
* [ ] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [ ] OpenCL-Headers
    * [ ] OpenCL-CLHPP
    * [ ] OpenCL-ICD-Loader
    * [ ] OpenCL-SDK
* [x]  CTS PRs for new extensions:
    * [x] cl_khr_integer_dot_product v2 - https://github.com/KhronosGroup/OpenCL-CTS/pull/1317
    * [ ] cl_khr_semaphore
    * [ ] cl_khr_external_semaphore
    * [ ] cl_khr_external_memory

**Comment by bashbaug** [comment]
We'll tag and release the ecosystem repos for the November spec instead, and we have CTS and C++ binding support for all of the non-provisional extensions, so I am closing this issue.
