### ISSUE TITLE
November 2021 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#723]
This issue is to track tasks related to the November 2021 spec release.

* [x] Merge any last-minute fixes
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.10
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/111
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/112
* [x] Add extension headers to OpenCL-Headers
    * [x] https://github.com/KhronosGroup/OpenCL-Headers/pull/182
* [x] ~Update OpenCL C++ bindings~ - no updates planned for this release
* [x] Update OpenCL-SDK submodules - https://github.com/KhronosGroup/OpenCL-SDK/pull/38
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2022.01.04
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2.0.16
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2022.01.04
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2022.01.05
* [x]  CTS PRs for new extensions:
    * [x] cl_khr_async_copy_fence - see https://github.com/KhronosGroup/OpenCL-CTS/issues/1422
    * [x] cl_khr_extended_async_copies - see https://github.com/KhronosGroup/OpenCL-CTS/issues/1423
    * [x] cl_khr_expect_assume - see https://github.com/KhronosGroup/OpenCL-CTS/issues/1424
    * [x] cl_khr_command_buffer (provisional) - https://github.com/KhronosGroup/OpenCL-CTS/pull/1368

**Comment by bashbaug** [comment]
I've created CTS issues for the remaing extension coverage, so closing this issue.
