### ISSUE TITLE
May 2022 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#790]
This issue is to track tasks related to the May 2022 spec release.

* [x] Merge any last-minute fixes
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.11
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/121
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/122
* [x] Add extension headers to OpenCL-Headers
* [x] Update OpenCL C++ bindings
* [x] Update OpenCL-SDK submodules - https://github.com/KhronosGroup/OpenCL-SDK/commit/466e28b47554aa0c0bd4d131ccd7ed6b2a7b6545
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2022.05.18
        * [x] merge https://github.com/KhronosGroup/OpenCL-Headers/pull/196 before tagging?
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2022.05.18
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2022.05.18
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2022.05.18
* [x]  CTS PRs for new extensions:
    * [x] cl_khr_subgroup_rotate - https://github.com/KhronosGroup/OpenCL-CTS/pull/1435
    * [x] cl_khr_work_group_uniform_arithmetic - https://github.com/KhronosGroup/OpenCL-CTS/issues/1508

**Comment by bashbaug** [comment]
I added a CTS issue to track missing coverage for cl_khr_uniform_work_group_arithmetic, so we can close this checklist issue.
