### ISSUE TITLE
September 2022 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#845]
This issue is to track tasks related to the September 2022 spec release.

* [x] Merge any last-minute fixes
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.12
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/128
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/129
* [x] Add extension headers to OpenCL-Headers
* [x] ~~Update OpenCL C++ bindings (needed?)~~
* [x] Update OpenCL-SDK submodules and project version - https://github.com/KhronosGroup/OpenCL-SDK/pull/60
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2022.09.30
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2022.09.30
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2022.09.30
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2022.09.30
* [x]  CTS PRs for new extensions:
    * [x] cl_khr_command_buffer_mutable_dispatch - https://github.com/KhronosGroup/OpenCL-CTS/issues/1481

**Comment by EwanC** [comment]
For `cl_khr_command_buffer_mutable_dispatch` CTS PRs we can link this CTS issue https://github.com/KhronosGroup/OpenCL-CTS/issues/1481

**Comment by bashbaug** [comment]
Great, thanks!  I think that's all we need now to close this issue.
