### ISSUE TITLE
February 2023 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#876]
This issue is to track tasks related to the February 2023 spec release.

* [x] Merge any last-minute fixes
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.13
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/132
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/134
* [x] ~~Add extension headers to OpenCL-Headers~~ - nothing required for this release?
* [x] ~~Update OpenCL C++ bindings~~ - nothing required for this release?
* [x] Update OpenCL-SDK submodules and project version - https://github.com/KhronosGroup/OpenCL-SDK/pull/64
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2023.02.06
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2023.02.06
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2023.02.06
        - note new release naming for: https://github.com/KhronosGroup/OpenCL-CLHPP/issues/185
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2023.02.06
* [x]  ~~CTS PRs for new extensions:~~ - nothing required for this release?

**Comment by bashbaug** [comment]
All tasks complete, closing.
