### ISSUE TITLE
April 2023 Release Checklist

### ISSUE THREAD

**Issue by bashbaug** [KhronosGroup/OpenCL-Docs#909]
This issue is to track tasks related to the April 2023 spec release.

* [x] Merge any last-minute fixes
    * [x] https://github.com/KhronosGroup/OpenCL-Docs/pull/908
    * [x] https://github.com/KhronosGroup/OpenCL-Docs/pull/910
* [x] Tag the spec sources - https://github.com/KhronosGroup/OpenCL-Docs/releases/tag/v3.0.14
* [x] Build the specs and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/135
* [x] Build the reference pages and create an OpenCL-Registry PR to publish them - https://github.com/KhronosGroup/OpenCL-Registry/pull/136
* [x] Add extension headers to OpenCL-Headers
    * [x] https://github.com/KhronosGroup/OpenCL-Headers/pull/229
* [x] ~~Update OpenCL C++ bindings~~ - Nothing more planned.
* [x] Update OpenCL-SDK submodules and project version - https://github.com/KhronosGroup/OpenCL-SDK/pull/76
* [x] [Tag and release](https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/managing-releases-in-a-repository#creating-a-release) additional ecosystem repos:
    * [x] OpenCL-SDK - https://github.com/KhronosGroup/OpenCL-SDK/releases/tag/v2023.04.17
    * [x] OpenCL-Headers - https://github.com/KhronosGroup/OpenCL-Headers/releases/tag/v2023.04.17
    * [x] OpenCL-CLHPP - https://github.com/KhronosGroup/OpenCL-CLHPP/releases/tag/v2023.04.17
    * [x] OpenCL-ICD-Loader - https://github.com/KhronosGroup/OpenCL-ICD-Loader/releases/tag/v2023.04.17
* [x]  CTS PRs for new extensions
    * [x] cl_khr_command_buffer_multi_device - https://github.com/KhronosGroup/OpenCL-CTS/issues/1703

**Comment by EwanC** [comment]
For the CTS cl_khr_command_buffer_multi_device PR item, this test plan issue should suffice - https://github.com/KhronosGroup/OpenCL-CTS/issues/1703

**Comment by bashbaug** [comment]
All tasks are done - closing!
